[package]
name = "rustproxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.34", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
futures = "0.3"